### ISSUE TITLE
Error to run the assemble  command with WRF4.1.1_CMAQ5.3.2_twoway option

### ISSUE THREAD

**Issue by Ntmanh18196** [USEPA/CMAQ#160]
Hi Dr. Foley,
I'm a new user of WRF-CMAQ model, currently I have been compiling the this model with WRF4.1.1_CMAQ5.3.2_twoway option.
However, I got the problem at the 9 stage of the tutorials, which is displayed in the below:
`[weather@igplogin WRF-4.1.1]$ ./twoway/assemble 
cp: cannot stat ‘cmaq/complex_number_module.F90’: No such file or directory
grep: Makefile: No such file or directory
grep: Makefile: No such file or directory
grep: Makefile: No such file or directory
grep: Makefile: No such file or directory
grep: Makefile: No such file or directory
grep: Makefile: No such file or directory
wc: Makefile: No such file or directory
cpp_begin_line: Subscript out of range.
Please help me to address this issue.`
In addition, I didn't find the org directory in the twoway/misc path.
Thank you very much!
Bests,
-Manh

**Comment by kmfoley** [comment]
Dear Manh,  
Thank you for your interest in the WRF-CMAQ system.  I'm glad to see that you have posted this issue on our [User Forum](https://forum.cmascenter.org/t/error-to-run-the-assemble-program-with-the-wrf4-1-1-cmaq5-3-2-twoway-option/2476) since that is the best location for these types of questions. I will close this issue but I have alerted our developers of the WRF-CMAQ code of your forum post so that they can take a look at the error message and offer advice directly on the User Forum.
