### ISSUE TITLE
Does the latest version of WRF-CMAQ allow for modeling aerosol-cloud interactions? 

### ISSUE THREAD

**Issue by shanguanrain** [USEPA/CMAQ#214]
Hello, everybody!
I’m interested in learning if the latest version of WRF-CMAQ is capable of modeling aerosol-cloud interactions. Any references or resources you could share on this topic would be greatly appreciated.
Thanks!

**Comment by fisidi** [comment]
Thank you for your question and your interest in the CMAQ system. It looks a similar question was asked and responded to on the CMAS Forum (https://forum.cmascenter.org/t/does-the-latest-version-of-wrf-cmaq-allow-for-modeling-aerosol-cloud-interactions/4752). 

A team member and a community member has responded to the question there so I am closing this issue here!

Thanks Again!
