### ISSUE TITLE
Help for beginners with Installation of CMAQ and Required Libraries, running test cases

### ISSUE THREAD

**Issue by mugguin** [USEPA/CMAQ#217]
**Description:**
I am a beginner attempting to install the CMAQ model on my system. I have successfully installed all required software and libraries as per the documentation. However, I am facing challenges in installing CMAQ itself after downloading and unzipping the make file. The documentation mentions required libraries without providing clear instructions on how to install them.

**Scope and Impact:**
Other users who are new to CMAQ installation may encounter similar issues. Without clear installation instructions for the required libraries, beginners may find it difficult to proceed with setting up and running the CMAQ model.

**Solution:**
Currently, there is no known solution provided in the documentation for beginners facing this issue. I want to request clearer and more detailed instructions (maybe video tutorials with step by step installation guidance) on how to install the required libraries and subsequently build and run the CMAQ model. 

**Additional context:**
I am seeking guidance on whether there are video tutorials available that provide step-by-step instructions for beginners on how to install CMAQ, including setting up required libraries and running test cases. Any additional resources or tips would be greatly appreciated to facilitate my learning and successful installation of the CMAQ model.

**Comment by kmfoley** [comment]
Hi @mugguin, thank you for reaching out with your suggestion.  It sounds like perhaps you have found our **[CMAQ Tutorials](https://github.com/USEPA/CMAQ/blob/main/DOCS/Users_Guide/Tutorials/README.md)** on installing the prerequisite software for **[GCC](https://github.com/USEPA/CMAQ/blob/main/DOCS/Users_Guide/Tutorials/CMAQ_UG_tutorial_build_library_gcc.md)** or **[Intel](https://github.com/USEPA/CMAQ/blob/main/DOCS/Users_Guide/Tutorials/CMAQ_UG_tutorial_build_library_intel.md)** compilers and for running the **[CMAQ Test Case](https://github.com/USEPA/CMAQ/blob/main/DOCS/Users_Guide/Tutorials/CMAQ_UG_tutorial_benchmark.md)**.

If you could please post the specific information on what you are running and what issue you have run into with the installation process on the **CMAS User Forum (https://forum.cmascenter.org/)** following these guidelines:  [PLEASE READ before posting](https://forum.cmascenter.org/t/please-read-before-posting/)


At this time we are unable to offer a video version of our CMAQ tutorials.  However the CMAQ development team and the CMAS support team are available to help you with your specific issue with our current documentation.  We regularly update our documentation based on questions and issues that users post on the Forum.  

I will close this issue on our GitHub repository so that we can move our conversation over the User Forum.  

Thank you for your interest in CMAQ and for sharing your issue.
