### ISSUE TITLE
Two-Way Model Package Updates/Bug Fixes

### ISSUE THREAD

**Issue by zacadelman** [USEPA/CMAQ#78]
The twoway/reconfigure script is looking for a CCTM config file called cfg*.  The name of this file in the new CMAQv5.2 release is now *.cfg.

Change line 3 for twoway/reconfigure to:
set cfg_file = `ls -1 cmaq/*.cfg`

**Comment by zacadelman** [comment]
Update the Build Instructions documentation to say that the user must set the variable FC to either ifort, pgi, or gfort before running the command twoway/assemble (8th bullet in the build instructions section)

**Comment by zacadelman** [comment]
Line 43 of twoway/reconfigure need to terminate the sed command by adding a "/" after the 132:

sed 's/-ffixed-form/-ffixed-form -ffixed-line-length-132/' \

**Comment by zacadelman** [comment]
Update twoway/reconfigure so that LIOAPI in configure.wrf is set to lib:

#if ($FC == ifort) then
#   echo "LIOAPI  = Linux2_x86_64ifort" >> __temp
#else if ($FC == pgi) then
#   echo "LIOAPI  = Linux2_x86_64pg" >> __temp
#else if ($FC == gfort) then
#   echo "LIOAPI  = Linux2_x86_64gfort" >> __temp
#endif
   echo "LIOAPI  = lib" >> __temp

**Comment by zacadelman** [comment]
Add a note to the documentation that if Gfortran is used to compile WRF-CMAQ, it must be newer than v5.0 (requirement of WRF3.8).

**Comment by zacadelman** [comment]
Change line 3 of twoway/misc/Makefile.twoway.part1 from 

 IOAPI_INC_PATH = $(IOAPI)/ioapi/fixed_src

to

 IOAPI_INC_PATH = $(IOAPI)/include_files

**Comment by zacadelman** [comment]
Variable biogon is undefined in the script twoway_model_run_script

**Comment by dwongepa** [comment]
* The twoway/reconfigure script is looking for a CCTM config file called cfg*.

  has been addressed

* Update the Build Instructions documentation to say that the user must set the variable FC to either ifort, pgi, or gfort before running the command twoway/assemble (8th bullet in the build instructions section)

  FC is inherited from configure.wrf so user does not need to set it

* Line 43 of twoway/reconfigure need to terminate the sed command by adding a "/" after the 132

  has bee addressed

* Update twoway/reconfigure so that LIOAPI in configure.wrf is set to lib

  I think we should keep the traditional notation Linux2_x86_* where * is a specific compiler, e.g. 64ifort or 64pg

* Add a note to the documentation that if Gfortran is used to compile WRF-CMAQ, it must be newer than v5.0 (requirement of WRF3.8)

  agree

* Change line 3 of twoway/misc/Makefile.twoway.part1 

  I think we should keep the traditional IOAPI path structure, i.e. IOAPI_INC_PATH = $(IOAPI)/ioapi/fixed_src

* Variable biogon is undefined in the script twoway_model_run_script

  That line should be replaced with

        if ( $CTM_BIOGEMIS == 'Y' ) then

  and it has been addressed
